In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

#DATADIR = "X:/Datasets/PetImages"

#CATEGORIES = ["Dog", "Cat"]
dirname = ''
train_path = os.path.join(dirname, 'OCT2017/train')
train_normal_pth = os.path.join(train_path, 'NORMAL')
train_dme_pth = os.path.join(train_path, 'DME')
train_drusen_pth = os.path.join(train_path, 'DRUSEN')
train_cnv_pth = os.path.join(train_path, 'CNV')
    
test_path = os.path.join(dirname, 'OCT2017/test')
test_normal_pth = os.path.join(test_path, 'NORMAL')
test_dme_pth = os.path.join(test_path, 'DME')
test_drusen_pth = os.path.join(test_path, 'DRUSEN')
test_cnv_pth = os.path.join(test_path, 'CNV')
    
val_path = os.path.join(dirname, 'OCT2017/val')
val_normal_pth = os.path.join(val_path, 'NORMAL')
val_dme_pth = os.path.join(val_path, 'DME')
val_drusen_pth = os.path.join(val_path, 'DRUSEN')
val_cnv_pth = os.path.join(val_path, 'CNV')



In [2]:
training_data = []
testing_data= []
val_data = []
DATADIR = "OCT2017/"
data = ["train/","test/","val/"]
CATEGORIES = ["NORMAL","DME","DRUSEN","CNV"]
IMG_SIZE = 160
def create_training_data():
    for i in range(len(data)):
    
        for category in CATEGORIES:  # do dogs and cats
        
            path = os.path.join(DATADIR,data[i],category)  # create path to dogs and cats
            class_num = CATEGORIES.index(category)  # get the classification  (0 or a 1). 0=dog 1=cat

            for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
                try:
                    if i == 0:
                        img_array = cv2.imread(os.path.join(path,img))  # convert to array
                        #print(img_array.shape)
                        
                        img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                        #print(img_array.shape)
                        training_data.append([img_array, class_num])  # add this to our training_data
                        
                    if i == 1:
                        img_array = cv2.imread(os.path.join(path,img))  # convert to array
                        img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                        testing_data.append([img_array, class_num])  # add this to our training_data
                    if i == 2:
                        img_array = cv2.imread(os.path.join(path,img))  # convert to array
                        img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                        val_data.append([img_array, class_num])  # add this to our training_data
                except Exception as e:  # in the interest in keeping the output clean...
                    print(e)
                    pass
                
                #except OSError as e:
                #    print("OSErrroBad img most likely", e, os.path.join(path,img))
                #except Exception as e:
                #    print("general exception", e, os.path.join(path,img))

create_training_data()

print(len(training_data))

100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 249.95it/s]

83484


In [3]:
import random

random.shuffle(training_data)
X_TRAIN = []
y_train = []

for features,label in training_data:
    X_TRAIN.append(features)
    y_train.append(label)



X_train =  np.asarray(X_TRAIN, dtype=np.float32)
y_train = np.array(y_train)

In [4]:
print((X_val))

NameError: name 'X_val' is not defined

In [5]:
print(X_test.shape)

NameError: name 'X_test' is not defined

In [7]:
import random

random.shuffle(val_data)
X_val = []
y_val = []



random.shuffle(testing_data)
X_test = []
y_test = []

for features,label in tqdm(testing_data):
    X_test.append(features)
    y_test.append(label)

#print(X_test[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

X_test = np.array(X_test)
y_test = np.array(y_test)




100%|██████████████████████████████████████████████████████████████████████████████████████████| 968/968 [00:00<00:00, 967839.40it/s]


In [8]:
import imgaug as ia
import imgaug.augmenters as iaa

seq = iaa.Sequential([
        iaa.Fliplr(0.5),
        iaa.Flipud(0.5),
        iaa.Invert(0.5),
        iaa.Rotate((-45, 45)),
        iaa.GaussianBlur(sigma=(0, 3.0)) 
        # blur images with a sigma of 0 to 3.0
    ])
def augment_seq(img):
        seq_det = seq.to_deterministic()
        aug_image = seq_det.augment_image(img)
        return aug_image
def augment(img):
    pass
    
#images_aug = seq(images = X_TRAIN)

In [9]:
#print(len(images_aug))

In [10]:
def train_part34(model_init_fn, optimizer_init_fn, num_epochs=1, is_training=False):
 ############################################################################
# TODO: Train a model on CIFAR-10.                 #
############################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    model = model_init_fn()
    opt = optimizer_init_fn()
    model.compile(optimizer=opt, loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics=['accuracy']) 
    loss = model.fit(X_TRAIN, y_train, batch_size=64, epochs=num_epochs)
    return model
# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
############################################################################
#                            END OF YOUR CODE                              #
############################################################################

In [12]:
class Dataset(object):
    def __init__(self, X, y, batch_size, shuffle=False):
        """
        Construct a Dataset object to iterate over data X and labels y
        
        Inputs:
        - X: Numpy array of data, of any shape
        - y: Numpy array of labels, of any shape but with y.shape[0] == X.shape[0]
        - batch_size: Integer giving number of elements per minibatch
        - shuffle: (optional) Boolean, whether to shuffle the data on each epoch
        """
        assert X.shape[0] == y.shape[0], 'Got different numbers of data and labels'
        self.X, self.y = X, y
        self.batch_size, self.shuffle = batch_size, shuffle

    def __iter__(self):
        N, B = self.X.shape[0], self.batch_size
        idxs = np.arange(N)
        if self.shuffle:
            np.random.shuffle(idxs)
        return iter((self.X[i:i+B], self.y[i:i+B]) for i in range(0, N, B))


train_dset = Dataset(X_train, y_train, batch_size=64, shuffle=True)
#val_dset = Dataset(X_val, y_val, batch_size=64, shuffle=False)
test_dset = Dataset(X_test, y_test, batch_size=64)

In [16]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0][:,:,0])

(83484, 160, 160, 3)
(160, 160, 3)
[[ 0. 17. 15. ... 22.  0.  0.]
 [ 1.  4.  9. ...  5.  1.  2.]
 [ 4. 18. 13. ... 17.  7.  4.]
 ...
 [ 2.  5.  7. ...  3. 12.  5.]
 [ 0.  2. 11. ... 12. 11.  6.]
 [ 2.  0.  8. ...  0.  9.  3.]]


In [19]:
import tensorflow as tf
# Set up some global variables
USE_GPU = True

if USE_GPU:
    device = '/device:GPU:0'
else:
    device = '/cpu:0'

# Constant to control how often we print when training models
print_every = 100

print('Using device: ', device)
class CustomConvNet(tf.keras.Model):
    def __init__(self):
        super(CustomConvNet, self).__init__()
        ############################################################################
        # TODO: Construct a model that performs well on CIFAR-10                   #
        ############################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

        self.conv1 = tf.keras.layers.Conv2D(32, (3,3), padding="same")
        self.relu1 = tf.keras.layers.Activation("relu")
        self.conv2 = tf.keras.layers.Conv2D(32, (3,3), padding="same")
        self.relu2 = tf.keras.layers.Activation("relu")
        self.pool1 = tf.keras.layers.MaxPool2D(pool_size=(2, 2), strides=None, padding='valid')
        
        self.conv3 = tf.keras.layers.Conv2D(32, (5,5), padding="same")
        self.relu3 = tf.keras.layers.Activation("relu")
        self.conv4 = tf.keras.layers.Conv2D(32, (5,5), padding="same")
        self.relu4 = tf.keras.layers.Activation("relu")
        self.pool2 = tf.keras.layers.MaxPool2D(pool_size=(2, 2), strides=None, padding='valid')
        
        
        self.flatten2 = tf.keras.layers.Flatten()
        self.dense1 = tf.keras.layers.Dense(512)
        self.relu5 = tf.keras.layers.Activation("relu")
        self.drop = tf.keras.layers.Dropout(0.2)
        self.dense2 = tf.keras.layers.Dense(10)
        self.softmax = tf.keras.layers.Activation("softmax")

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        ############################################################################
        #                            END OF YOUR CODE                              #
        ############################################################################
    
    def call(self, input_tensor, training=False):
        ############################################################################
        # TODO: Construct a model that performs well on CIFAR-10                   #
        ############################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

        x = self.conv1(input_tensor)
        x = self.relu1(x)
        x = self.conv2(x)
        x = self.relu2(x)
        x = self.pool1(x)
        

        x = self.conv3(x)
        x = self.relu3(x)
        x = self.conv4(x)
        x = self.relu4(x)
        x = self.pool2(x)
        
        x = self.flatten2(x)
        x = self.dense1(x)
        x = self.relu5(x)
        x = self.drop(x)
        x = self.dense2(x)
    
        x = self.softmax(x)
        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        ############################################################################
        #                            END OF YOUR CODE                              #
        ############################################################################
        
        return x

device = '/device:GPU:0'   # Change this to a CPU/GPU as you wish!
# device = '/cpu:0'        # Change this to a CPU/GPU as you wish!
print_every = 700
num_epochs = 10

model = CustomConvNet()

def model_init_fn():
    return CustomConvNet()

def optimizer_init_fn():
    learning_rate = 1e-3
    return tf.keras.optimizers.Adam(learning_rate) 
print('Train')
def train_part2(model_fn, init_fn, learning_rate, epochs):
    """
    Train a model on CIFAR-10.
    
    Inputs:
    - model_fn: A Python function that performs the forward pass of the model
      using TensorFlow; it should have the following signature:
      scores = model_fn(x, params) where x is a TensorFlow Tensor giving a
      minibatch of image data, params is a list of TensorFlow Tensors holding
      the model weights, and scores is a TensorFlow Tensor of shape (N, C)
      giving scores for all elements of x.
    - init_fn: A Python function that initializes the parameters of the model.
      It should have the signature params = init_fn() where params is a list
      of TensorFlow Tensors holding the (randomly initialized) weights of the
      model.
    - learning_rate: Python float giving the learning rate to use for SGD.
    """
    
    
    params = init_fn()  # Initialize the model parameters            
    for e in range(epochs):    
        for t, (x_np, y_np) in enumerate(train_dset):
            # Run the graph on a batch of training data.
            loss = training_step(model_fn, x_np, y_np, params, learning_rate)

            # Periodically print the loss and check accuracy on the val set.
            if t % print_every == 0:
                print('Epoch %d, iteration %d, loss = %.4f' % (e, t, loss))
                print('Validation:')
                check_accuracy(val_dset, model_fn, params)
    return params
def training_step(model_fn, x, y, params, learning_rate):
    with tf.GradientTape() as tape:
        scores = model_fn(x, params) # Forward pass of the model
        loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=scores)
        total_loss = tf.reduce_mean(loss)
        grad_params = tape.gradient(total_loss, params)

        # Make a vanilla gradient descent step on all of the model parameters
        # Manually update the weights using assign_sub()
        for w, grad_w in zip(params, grad_params):
            w.assign_sub(learning_rate * grad_w)
                        
        return total_loss
    
trained_params =train_part2(model_init_fn, epochs=num_epochs)




Using device:  /device:GPU:0
Train


TypeError: train_part2() missing 1 required positional argument: 'learning_rate'